/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_STUBSERVER_H_
#define JSONRPC_CPP_STUB_STUBSERVER_H_

#include <jsonrpccpp/server.h>

class stubserver : public jsonrpc::AbstractServer<stubserver>
{
    public:
        stubserver(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<stubserver>(conn, type)
        {
            this->bindAndAddNotification(jsonrpc::Procedure("setParam", jsonrpc::PARAMS_BY_NAME, "args",jsonrpc::JSON_OBJECT, NULL), &stubserver::setParamI);
            this->bindAndAddMethod(jsonrpc::Procedure("getParam", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &stubserver::getParamI);
        }

        inline virtual void setParamI(const Json::Value &request)
        {
            this->setParam(request["args"]);
        }
        inline virtual void getParamI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getParam();
        }
        virtual void setParam(const Json::Value& args) = 0;
        virtual Json::Value getParam() = 0;
};

#endif //JSONRPC_CPP_STUB_STUBSERVER_H_
